---
title: "Wordle Stats"
output: 
  html_document:
    code_folding: show
    df_print: kable
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = TRUE,
  warning = FALSE,
  message = FALSE,
  comment = ""
)


# limit rows displayed
options(tibble.print_min = 5)
#options(crayon.enabled = TRUE)

#old.hooks <- fansi::set_knit_hooks(knitr::knit_hooks)
```

#### Data from the NYT
The word list comes from [this]("https://www.nytimes.com/games/wordle/main.18637ca1.js") JS file. Look for `var Ma=` to see the list. You can see the full code [here](https://github.com/rjake/one-off-projects/blob/main/R/wordle/input/download-data.R)

```{r workspace}
library(tidyverse)
library(glue)
library(gt)
library(scales)
library(simplecolors)

# read in NYT data
raw_words <-
  read_csv("input/nyt_word_list.csv") |>
  as_tibble() |> 
  print()
```

```{r word-letters}
# Break out each letter into its own column
word_letters <-
  raw_words |>
  separate(
    col = word,
    sep = "",
    into = paste0("x", 0:5),
    remove = FALSE
  ) |>
  select(-x0) |>
  print()

```


```{r word-letters-long}
# Pivot the data to long-form and tally up frequencies
word_letters_long <- 
  word_letters |> 
  pivot_longer(
    cols = starts_with("x"),
    names_to = "position",
    values_to = "letter"
  ) |> 
   # times letter was used at all 
  add_count(letter, name = "letter_freq") |> 
  # times letter was used in position 
  add_count(letter, position, name = "position_freq") |> 
  print()
```

```{r word-letter-freq}
# Pivot wider
word_letter_freq <-
  word_letters_long |> 
  select(word, pos = letter, position, freq = position_freq) |>
  pivot_wider(
    names_from = position,
    values_from = c(pos, freq)
  ) |>
  rename_all(str_remove_all, "pos_") |> 
  print()
```

```{r letter-stats}
# Letters by total count and frequency in positions 1:5
letter_stats <- 
  word_letters_long |> 
  distinct(letter, letter_freq, position, position_freq) |> 
  pivot_wider(
    names_from = position,
    values_from = position_freq,
    values_fill = 0
  ) |> 
  arrange(desc(letter_freq))

```

```{r gt-letter-stats, echo=FALSE}
# set colors for heatmaps
gradient <- c(
  "white", 
  sc("mutedteal3")
)

# print ----
letter_stats |>
  rename(`# words` = letter_freq) |> 
  rename_at(
    vars(starts_with("x")), 
    ~str_remove(.x, "x")
  ) |> 
  gt() |>
  tab_options(
    container.overflow.y = TRUE,
    container.height = 300
  ) |> 
  data_color(
    columns = -letter,
    colors = scales::col_numeric(
      palette = gradient,
      domain = NULL
    )
  )
```

```{r word-stats}
# Create metrics for each word. letter_stats$letter is a factor so `letters
word_stats <- 
  word_letters_long |> 
  mutate(
    letter = factor(letter, levels = letter_stats$letter, ordered = TRUE),
    letter_ord = as.integer(letter)
  ) |> 
  group_by(word) |> 
  arrange(letter) |> 
  summarise(
    alpha = paste(sort(as.character(letter)), collapse = ""),
    n_letter = n_distinct(letter),
    n_1_5 = sum(letter %in% letter_stats$letter[1:5]),
    n_6_10 = sum(letter %in% letter_stats$letter[6:10]),
    n_10_15 = sum(letter %in% letter_stats$letter[10:15]),
    n_12_26 = sum(letter %in% letter_stats$letter[12:26]),
    # are the letters closest to the top (1:26, lower is better) 
    mean_letter_rank = mean(letter_ord),
    # are the letter closer to their most common positions (higher is better)
    mean_pos_freq = mean(position_freq) 
    #,mean_letter_freq = mean(letter_freq),sum_letter_freq = sum(letter_freq)
  ) |> 
  ungroup() |> 
  arrange(mean_letter_rank) |> 
  print()
```

```{r echo=FALSE}
# write_csv(word_stats, "R/wordle/output/word-stats.csv")
```

```{r}
# find words that have 5 distinct values
distinct_letters <-
  word_stats |> 
  filter(n_letter == 5) |> 
  print()

# roll-up words by patterns (for regex)
as_patterns <-
  distinct_letters |>
  # roll up words by best placement
  group_by(alpha) |> 
  arrange(desc(mean_pos_freq)) |> 
  summarise(
    words = paste(word, collapse = ","),
    mean_letter_rank = mean(mean_letter_rank), # same across all values
    across(matches("n_\\d"), mean),
  ) |> 
  ungroup() |> 
  # create pattern column, move to front
  # mutate(
  #   pattern = str_replace_all(alpha, "(.)(?=.)", "\\1|"),
  #   .before = everything()
  # ) |> 
  arrange(mean_letter_rank) |> 
  print()


# best starting words primarily from letters 1-5: later, irate, stare, arose, stare, crate
as_patterns |> 
  filter(n_1_5 >= 4) |> 
  head(3)

# best 2nd word from 6-10: slain, slice, since, sonic, sling, cling, slink, slick
as_patterns |> 
  filter(n_6_10 >=  4) |> 
  head(3)

# best 3rd words from letters 10-15: duchy, dutch, pouch, punch, pushy, chump, dumpy, pudgy
as_patterns |> 
  filter(n_10_15 >= 4) |> 
  arrange(desc(n_10_15), mean_letter_rank) |> 
  head(3)

# best remaining words from rest of alphabet: gawky, maybe, foamy, gumbo, buxom, jumbo
as_patterns |> 
  filter(n_12_26 >= 3) |> 
  filter(!str_detect(alpha, "[rtlsncdhp]")) |> 
  arrange(desc(n_12_26)) |> 
  head(3)
```

```{r}
# Look for next best word once existing letters have been used
find_next <- function(use_pattern, suffix = "") {
  
  as_patterns |>
    # see which are used the fewest
    mutate(found = str_count(alpha, glue("[{use_pattern}]"))) |> 
    arrange(found, mean_letter_rank) |> 
    slice(1) |> 
    distinct(alpha, words, rank = mean_letter_rank) |> 
    rename_all(paste0, suffix)

}

# best starting word
find_next(use_pattern = ".")

# best word after [aelrt] (later, alter, alert)
find_next(use_pattern = "aelrt") 

# best word after [aelrt] + [cinos] (sonic, scion)
find_next(use_pattern = "aelrtcinos")
```

```{r best-sequences, class.source = 'fold-hide'}
# Find best sequences
best_sequences <-
  as_patterns |> 
  filter(n_1_5 >= 4) |> 
  distinct(
    alpha_1 = alpha,
    words_1 = words,
    rank_1 = mean_letter_rank
  ) |> 
  mutate(
    second = map(
      .x = alpha_1, 
      .f = find_next, 
      suffix = "_2"
    )
  ) |> 
  unnest_wider(second) |> 
  mutate(
    third = map(
      .x = paste0(alpha_1, alpha_2),
      .f = find_next,
      suffix = "_3"
    )
  ) |>
  unnest_wider(third) |>
  mutate(
    forth = map(
      .x = paste0(alpha_1, alpha_2, alpha_3),
      .f = find_next,
      suffix = "_4"
    )
  ) |>
  unnest_wider(forth) |>
  mutate(
    n_distinct = map_chr(
      .x = paste(alpha_1, alpha_2, alpha_3, alpha_4),
      .f =
        ~ str_split(.x, "") |>
        unlist() |>
        unique() |>
        length()
    ),
    sum_rank = (rank_1 + rank_2 + rank_3)
  ) |> 
  arrange(desc(n_distinct), sum_rank)
```

```{r}
head(best_sequences, 5)
```

```{r, class.source = 'fold-hide'}
# Create plot
best_sequences |> 
  head(10) |> 
  select(starts_with(words), starts_with("rank")) |> 
  mutate(order = row_number()) |> 
  mutate_all(as.character) |> 
  pivot_longer(
    -order,
    names_to = c("type", "id"),
    names_sep = "_"
  ) |> 
  pivot_wider(
    names_from = type,
    values_from = value
  ) |> 
  mutate(across(c(order, id, rank), as.numeric)) |> #print()
  ggplot(aes(order, id)) +
  geom_tile(aes(fill = rank), alpha = 0.8) +
  geom_text(
    aes(label = str_replace_all(words, ",", "\n")),
    size = 2.5
  ) +
  scale_fill_viridis_c(
    option = "D",
    direction = -1
  ) +
  scale_x_continuous(expand = expansion()) +
  scale_y_reverse() +
  coord_fixed() +
  theme(
    panel.background = element_rect(fill = "white", color = "white"),
    axis.title = element_blank(),
    axis.text.x = element_blank(),
    axis.ticks.x = element_blank()
  ) +
  labs(
    title = "Best Plays",
    fill = "Letter Rank"
  )


# best series: from nytimes js
# adore    # arose    # route    # trope
# until    # unlit    # slain    # slain
# chasm    # champ    # champ    # duchy
# gawky    # bawdy    # bawdy    # gumbo

# best series: from dictionary
# arose    # arose 
# unlit    # clint 
# champ    # dumpy 
# gawky    # hawks






```


```{r}
# solving wordle
# example: floor - has [lor] but not [ais...], [l] is the 2nd letter
str_detect_each <- function(x, letters) {
  pattern <-
    str_split(letters, "")[[1]] |> 
    sort() |> 
    paste(collapse = "|")

  matches <-
    str_extract_all(x, pattern) |>
    map(pluck) |> 
    map(sort) |> 
    map_chr(paste, collapse = "|")
  
  matches == pattern
}


word_stats |>
  # green
  filter(str_detect(word, "s.a..")) |>     # these are filled in
  # yellow
  filter(str_detect_each(word, "te")) |>   # has these other letters
  filter(!str_detect(word, "...[t].")) |>  # t is not in the 3rd position
  # grey
  filter(!str_detect(word, "[liopr]"))     # none of these letters
```

