---
title: "Glasses Fit"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    source_code: embed
    theme: lumen
runtime: shiny
---

```{r input_demo, eval = interactive()}
input <- list(
  pd = 59,
  offset = c(4, 6),
  frame = c(125, 130),
  bridge = c(17, 20),
  lens = c(40, 50)
)

shiny::reactiveConsole(TRUE)
```

```{css}
/* body */
body {
  font-size: 11px;
}


/* input reactive sliders */
.irs-grid-text {
  font-size: 11px;
}


.irs--shiny .irs-bar {
    top: 26px;
    height: 7px;
}


.irs--shiny .irs-handle {
    top: 22px;
    width: 14px;
    height: 14px;
}
```

```{r setup, include=FALSE}
library(tidyverse)
library(glue)
library(shiny)
library(shinyWidgets)
library(simplecolors)
library(gt)

enableBookmarking(store = "url")

```

Sidebar {.sidebar data-width=300}
-----------------------------------------------------------------------

```{r inputs}
# input ----
widget_label <- function(title, text = "") {
  p(
    strong(title), 
    br(),
    text, 
    style = "margin: 0px;"
  )
}

my_slider <- function(inputId, label, ...) {
  sliderInput(
    inputId = inputId,
    label = label,
    ticks = FALSE,
    step = 1,
    #post = "mm",
    ...
  ) 
}

## $ pd ----
my_slider(
  inputId = "pd",
  label = 
    widget_label(
      title = "Pupilary Distance (mm)",
      text = "Distance from pupil to pupil."
    ),
  min = 35, 
  max = 85,
  value = 59
)

## $ offset ----
my_slider(
  inputId = "offset",
  label = 
    widget_label(
      title = "Offset Tolerance (mm)", 
      text = 'How "off from center" can the glasses be based on your PD? Lower will place your pupils closer to the center. Higher will place your pupils towards the edge of the frame.'
    ),
  min = -8,
  max = 8,
  value = c(4, 6)
)

## $ lens ----
my_slider(
  inputId = "lens",
  label = widget_label("Lens Width (mm)"),
  min = 35,
  max = 70,
  value = c(40, 50)
)

## $ bridge ----
my_slider(
  inputId = "bridge",
  label = widget_label("Bridge Width (mm)"),
  min = 10,
  max = 30,
  value = c(17, 20)
)

## $ frame
my_slider(
  inputId = "frame",
  label = widget_label("Frame Width (mm)"),
  min = 115,
  max = 160,
  value = c(125, 135)
)
```

```{r bookmark}
shiny::bookmarkButton()
```


```{r base_df}
# * base_df() ----
base_df <- reactive({
  tibble(
    lens = seq(input$lens[1], input$lens[2])
  ) |> 
    expand(
      lens, 
      bridge = seq(input$bridge[1], input$bridge[2])
    ) |> 
    mutate(
      pd = lens - (input$pd - bridge)
    ) 
})
```

Column
-----------------------------------------------------------------------

### Best Fit

```{r gt}
gt::render_gt({
  
  df <- base_df()

  prep_df <-
    df |> 
    mutate(
      .by = bridge,
      min_lens = min(lens[pd >= min(input$offset)], na.rm = TRUE),
      max_lens = max(lens[pd <= max(input$offset)], na.rm = TRUE)
    ) |> 
    pivot_wider(names_from = lens, values_from = pd) |> 
    mutate(
      lens_range = glue("{min_lens}-{max_lens}"),
      zenni =
        glue(
          'https://www.zennioptical.com/b/all-glasses?filter=\\
          prod_bridge{is}{bridge_range}{and}\\
          prod_frame_width{is}{frame_range}{and}\\
          prod_lens_width{is}{lens_range}{and}\\
          single_pd{is}{input$pd}&pt=single',
          and = "%2C",
          is = "%3A",
          bridge_range = glue("{bridge}-{bridge}"),
          frame_range = glue("{min(input$frame)}-{max(input$frame)}")
        )
    ) |>
    mutate(
        zenni = map2(
        .x = zenni,
        .y = lens_range,
        .f = 
          ~htmltools::a(
            href = .x, .y,
            target = "_blank",
            rel = "noopener noreferrer"
          ) |> 
          as.character() |> 
          gt::html()
        )
    )
    
  prep_df |> 
    select(-matches("lens")) |> 
    gt::gt(rowname_col = "bridge") |> 
    gt::tab_stubhead(label = "bridge") |> 
    gt::tab_spanner(
      label = "Lens Width", 
      columns = matches("\\d")
    ) |> 
    gt::tab_options(
      data_row.padding = px(1)
    ) |> 
    #fmt_markdown(columns = zenni) |> 
    gt::data_color(
      columns = -c(bridge, zenni),
      fn = 
        scales::col_bin(
          palette = sc("grey2", "yellow2", "yellow2", "grey2"),
          domain = c(-8, 8),
          bins = c(-9, min(input$offset), max(input$offset) + 1, 9)
        )
    )
  })


knitr::knit_exit()
  
```

# TODO:

* [ ] add hover text of pd values https://github.com/rstudio/gt/issues/181
* [x] add links for zenni
* [ ] glasses usa
* [ ] eyebuydirect
* [ ] warby parker
* [ ] add pause before rendering (debounce, throttle)

```{r}

  res <- microbenchmark::microbenchmark(
    times = 500,
    brackets =
      df |> 
      mutate(
        .by = bridge,
        min_lens = min(bridge[pd >= min(input$offset)]),
        max_lens = max(bridge[pd <= max(input$offset)])
      ),
    ifelse =   
      df |> 
      mutate(
        .by = bridge,
        min_lens = min(ifelse(pd >= min(input$offset), bridge, 0)),
        max_lens = max(ifelse(pd <= max(input$offset), bridge, 0))
      )
  )
  
  res
  
  ggplot(res, aes(time, expr)) + 
    geom_boxplot(outlier.shape = NA) +
    coord_cartesian(xlim = boxplot.stats(res$time)$stats |> range()) +
    scale_x_continuous(
      labels = ~.x / 1e6
    )
  
  ggplot2::autoplot(res)

```

