---
title: "Cirlce Packing"
author: "Jake"
date: "October 5, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### inspiration
[circlism](http://cse.iitkgp.ac.in/~pb/research/circlism/)
[google](https://www.google.com/search?q=digital+circlism)
[stackoverflow](https://mathematica.stackexchange.com/questions/40334/generating-visually-pleasing-circle-packs)
[Mitchell's Best-Candidate](https://bl.ocks.org/mbostock/1893974)
[fill svg shape](https://bl.ocks.org/gouldingken/8d0b7a05b0b0156da3b8)
[Voroni + tirangulation](https://www.researchgate.net/figure/273284325_fig7_Figure-7-An-example-of-a-Voronoi-diagram-in-Laguerre-geometry-for-a-set-of-multi-sized)
[inspiration](https://gravyanecdote.com/uncategorized/making-the-kraken-part-1-getting-the-image-and-data/)


*to plot `ggeom_sf()` the dev version of `ggplot` must be used. More detail can be found [here](http://strimas.com/r/tidy-sf/)
```{r workspace}
#library(devtools)
#devtools::install_github("tidyverse/ggplot2", force = T)
#devtools::install_github("sjp/grImport2")
#library(alphahull) #for optimized convex hulls
#library(ConR) #alpha hulls for clustering points
#library(doParallel)
#library(foreach)
library(imager)
library(maptools)
library(raster)
library(sf)
library(colorspace)
library(tidyverse)

options(warn = -1)
options(scipen = 999)

#library(svglite)
#library(grImport2)
#library(png)

image_path <- "input/R_logo.png"

image_name <- 
  basename(image_path) |> 
  tools::file_path_sans_ext()
```

```{r fns}
round_any <- function(x, accuracy) {
  round(x / accuracy) * accuracy
}

```

```{r prep-image}
#imager
#plot(boats)
#plot(load.image("starrynight.png"))
#plot(load.image("gears.png"))
#plot(load.image("fish_perch.png"))
#plot(load.image("orca.png"))
#plot(load.image("emma_sm.png"))
#plot(load.image("kraken.png"))
#plot(load.image(image_path))

modulo <- 2
blur_amt <- 0 #3000
min_color_pixels <- 50

load.image(image_path) |> 
  blur_anisotropic(amplitude = blur_amt) |> 
  plot()

image <- 
  load.image(image_path)

image_specs <-
  list(
    width = dim(image)[1] / 10,
    height = dim(image)[2] / 10
  )

prep_image <-
  image |> 
  rm.alpha() |> 
  RGBtoHSL() |> 
  as.data.frame() |> 
  as_tibble() |> 
  #filter(#y < 90,  x > 90) |>
  mutate(
    cc = recode(
      cc, 
      "1" = "orig_h", 
      "2" = "orig_s", 
      "3" = "orig_l"
    )
  ) |> 
  spread(key = cc, value = value) |> 
  mutate_all(as.numeric) |> 
  filter(
    (x %% modulo == 0 & y %% modulo == 0) |
    (x %% modulo == (modulo/2) & y %% modulo == (modulo/2))
  ) |>  
  mutate(y = max(y) - y) # reverse y axis


grid_base <-
  prep_image |> 
  mutate(
    orig_hex = hex(HLS(orig_h, orig_l, orig_s)),
    h = round_any(orig_h, 30), # 0.05
    l = round_any(orig_l, 0.25), # round(s/.33)*.33,
    s = round_any(orig_s, 0.25),
    hex = hex(HLS(h, l, s))
  ) |> 
  add_count(hex) |> 
  print()


n_distinct(grid_base$hex)

grid_base |> 
  filter(x > mean(x)) |> 
  ggplot(aes(x, y, color = hex)) +
  geom_point(size = 1) +
  #scale_y_reverse() +
  guides(color = FALSE) +
  coord_fixed() +
  scale_color_identity() +
  theme_bw()

grid_base |> 
  filter(x > mean(x)) |> 
  ggplot(aes(x, y, color = hex)) +
  geom_point() +
  scale_color_identity() +
  facet_wrap(~hex, nrow = 4) +
  theme_minimal() +
  theme(
    panel.background = element_rect(fill = "grey95"),
    panel.grid = element_line(color = "grey85"),
    axis.text = element_blank(),
    panel.border = element_rect(color = "grey40", fill = NA)
  )
```

### create concave hulls
```{r hulls}
#create convex hulls
color_points <- 
  grid_base |> 
  st_as_sf(coords = c("x", "y")) |> 
  select(hex, h, s, l) |> 
  mutate(
    area = 1,
    x = grid_base$x,
    y = grid_base$y
  ) |> 
  relocate(geometry, .after = everything()) |> 
  st_buffer(dist = modulo * 0.55, nQuadSegs = 4) |> 
  print()

color_points |> 
  filter(x < 10, y < 10) |> 
  ggplot() +
  geom_sf(aes(fill = hex), alpha = .8) +
  scale_fill_identity()

color_clusters <-
  color_points |> 
  select(hex) |> 
  group_by(hex) |> 
  summarize() |> 
  ungroup() |> 
  st_cast() |> 
  st_cast("POLYGON") |> 
  st_simplify(dTolerance = 1) %>%
  mutate(area = st_area(.)) |> 
  arrange(desc(area)) |> 
  st_buffer(0.5) |> 
  print()

color_clusters |> 
  #slice_sample(prop = 0.25) |> 
  ggplot() +
  geom_sf(aes(fill = hex), alpha = .8) +
  facet_wrap(~hex) +
  scale_fill_identity()
```




### main code
```{r for-loop}
color_circle_all <-
  color_clusters |>
  slice(0)

area_allowed <- floor(min(color_clusters$area))
buffer_min <- sqrt(area_allowed) / pi
get_iteration <- 1

system.time(
  for (cluster in 1:nrow(color_clusters)) {
    color_polygon <-
      color_clusters |>
      slice(cluster) |>
      filter(area > area_allowed)
    
    # plot(color_clusters$geometry, col = NA, add = F)
    # plot(color_circle_all$geometry, col = "red", add = T)
    # plot(color_polygon$geometry, col = color_polygon$hex, add = F)
    
    cluster_part <- 1
    area_left <- TRUE
    rows_left <- nrow(color_polygon)
    
    while (area_left || rows_left == 1) {
      if (!area_left && rows_left > 1) {
        # drop current row and go to next row
        color_polygon <-
          color_polygon |>
          slice(-1)
        
        # try next row
        next() # repeat current if logic
      }
      else {
        # update variable values
        get_area <- color_polygon$area[1]
        rows_left <- nrow(color_polygon)
        area_left <- get_area > area_allowed
        
        # take the first row from the data
        color_polygon_single <-
          color_polygon |>
          slice(1)
        
        # check to see if the buffer leaves enough space to plot
        color_buffer <-
          color_polygon_single |>
          st_buffer(-buffer_min) %>%
          mutate(area = st_area(.))
        
        # plot(color_buffer$geometry, add = T)
        
        color_polygon <-
          color_polygon |>
          slice(-1)
        
        if (nrow(color_buffer) == 0 || color_buffer$area == 0) {
          print("too small")
          area_left <- FALSE
          next()
        } else {
          # from calc, there is enough space to draw a circle
          # polygon needs to be a string for distance calc to work
          color_line <-
            color_polygon_single |>
            st_cast("LINESTRING")
          # plot(color_line$geometry, add = F)
          
          # find centroid of buffered region
          color_centroid <-
            color_buffer |>
            st_point_on_surface()
          
          # plot(color_centroid$geometry, add = T)
          
          # get the distance of this point
          color_dist <-
            st_distance(color_centroid[1, 1], color_line)
          
          # create a circle of this size (color_dist)
          color_circle <-
            color_centroid |>
            st_buffer(color_dist + .01)
          
          # plot(color_circle$geometry, add = T)
          
          # build dataset of circles
          color_circle_all <-
            rbind(color_circle, color_circle_all) |>
            st_cast("MULTIPOLYGON")
          
          color_new <-
            color_polygon_single |>
            st_difference(st_union(st_buffer(color_circle, 0.8))) |>
            st_cast("POLYGON") %>%
            mutate(area = st_area(.))
          
          # plot(color_new$geometry, add = F)
          if (nrow(color_new) == 0) {
            print("nothing left")
            area_left <- FALSE
          } else {
            # add new polygon shape/shapes to the color_polygon table
            color_polygon <-
              rbind(color_new, color_polygon)  |>
              arrange(desc(area)) |>
              filter(area > area_allowed) |>
              st_difference(st_union(color_circle))
            
            
            # conditions met
            cat(
              "cluster (row):", cluster, 
              " ///  part:", cluster_part, 
              " ///  iteration:", get_iteration, 
              " ///  remaining:", nrow(color_polygon), 
              "pieces left\n"
            )
          }
        }
        cluster_part <- cluster_part + 1
        get_iteration <- get_iteration + 1
        next()
      }
    }
  }
)

# saveRDS(color_circle_all, "color_circle_all.Rds")
```

```{r save-rds}

plot(
  color_circle_all$geometry, 
  col = color_circle_all$hex, 
  border = NA, 
  add = F
)

color_circle_all |> 
  filter(hex != "#FFFFFF") |> 
  ggplot() +
  geom_sf(aes(fill = hex), color = NA) +
  scale_fill_identity(guide = "none") +
  theme_void()

paste0("output/simple_",  image_name) |> 
  ggsave(
    device = "png",
    height = image_specs$height,
    width = image_specs$width,
    units = "mm"
  )

```


```{r find-colors}
get_mode <- function(x) {
  ux <- unique(x)
  ux[which.max(tabulate(match(x, ux)))]
}

grid_base_points <- 
  grid_base |>
  select(x, y, starts_with("orig_"), hex) |> 
  st_as_sf(coords = c("x", "y")) |> 
  st_buffer(modulo/2, nQuadSegs = 1)

#plot(grid_base_points$geometry)

color_circle_final <-
  color_circle_all |> 
  mutate(ID = row_number()) |> 
  st_join(grid_base_points, join = st_intersects)|> 
  group_by(ID) |> 
#  summarise(median_hex = get_mode(hex)) |> 
#  ungroup()
 summarise(
   h = median(orig_h),
   l = median(orig_l),
   s = median(orig_s)
  ) |> 
  ungroup() |> 
  mutate(median_hex = hex(HLS(h, l, s)))

color_circle_centroids <-
  color_circle_final |>
  arrange(median_hex) %>% 
  mutate(
    area = st_area(.),
    radius = sqrt(area)/pi
  ) |> 
  st_centroid() %>% 
  cbind(., st_coordinates(.)) |> 
  st_set_geometry(NULL)


#plot(color_circle_all$geometry[1:20], col = "red", add = T)

plot(
  color_circle_final$geometry, 
  col = color_circle_final$median_hex, 
  border = NA
)
```

### write
```{r final-output}

color_circle_final |> 
  filter(median_hex != "#FFFFFF") |> 
  ggplot() +
  geom_sf(aes(fill = median_hex), color = NA) +
  scale_fill_identity(guide = "none") +
  theme_void()


paste0("output/final_", image_name) |> 
  ggsave(
    device = "png",
    height = image_specs$height,
    width = image_specs$width,
    units = "mm"
  )



st_write(
  color_circle_final,
  paste0("output/shp/", image_name, ".shp")
)


# see how it would plot in tableau
color_circle_centroids |> 
  filter(median_hex != "#FFFFFF") |> 
  ggplot() +
  geom_point(
    aes(X, Y, fill = median_hex, size = pi*radius^2),
    shape = 21, stroke = 0.5
  ) +
  scale_fill_identity(guide = "none") +
  scale_size(
    guide = "none", 
    range = c(0.1, 20) # might need to be tweaked or adjust zoom
  ) + 
  coord_fixed() +
  theme_void()

# if it looks good, write to csv
write_csv(
  x = color_circle_centroids, 
  file = paste0("output/final_", image_name, ".csv")
)

```
